/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    println("Mucho gusto, Kotlin")

    val nombre: String = "Ignacio"
    val apellido: = "Esquivel"
    val fecha: Int = "22/4/25"

    println("Me llamo $nombre $apellido)
    println("Hoy es: $fecha")
}
fun Datos() {
    val edad: Int = "16"
    val altura: Double = "1.75cm"
    val esEstudiante: Boolean = true
    val fecha: Int = "22/4/25"

    println("Edad: $edad")
    println("Altura: $altura")
    println("Es estudiante: $esEstudiante")
    println("Hoy es: $fecha")
    }

